export { Navigation } from './Navigation'
export { Hero } from './Hero'
export { About } from './About'
export { Skills } from './Skills'
export { Experience } from './Experience'
export { Education } from './Education'
export { Footer } from './Footer'
