"""
Phase 2 Setup Agent

Creates and verifies Phase 2 scaffolding for the 7-layer architecture
without implementing business logic.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Tuple

from rich.console import Console
from rich.table import Table

console = Console()

PHASE2_SCAFFOLD: Dict[str, List[str]] = {
    "2_orchestrator": [
        "react_engine.py",
        "llm_factory.py",
        "agent_bus.py",
        "workflow_templates.py",
    ],
    "3_memory": [
        "conversation_store.py",
        "rag_indexer.py",
    ],
    "5_guardrails": [
        "input_validator.py",
        "command_validator.py",
        "rate_limiter.py",
        "security_filters.py",
    ],
    "6_telemetry": [
        "logger_config.py",
        "metrics.py",
        "tracer.py",
    ],
    "7_state": [
        "persistence.py",
        "recovery.py",
    ],
}


def _project_root() -> Path:
    return Path(__file__).parent.parent


def _template(layer: str, filename: str) -> str:
    module = filename.replace(".py", "")
    return f'''"""{layer}/{filename}

Phase 2 scaffold module.
TODO(phase2): Replace placeholders with production implementation.
"""

from __future__ import annotations


class {module.title().replace("_", "")}:  # noqa: D101
    def __init__(self) -> None:
        self.ready = False

    def status(self) -> str:
        """Return scaffold readiness marker for verification workflows."""
        return "scaffold-only"
'''


def generate_phase2_plan() -> Path:
    root = _project_root()
    plan_path = root / "agent" / "docs" / "PHASE2_SETUP_PLAN.md"
    plan_path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = [
        "# Phase 2 Setup Plan (Scaffold + Verification)",
        "",
        "This plan is generated by the setup agent.",
        "It does not implement Layer 2-7 runtime logic; it only prepares and verifies structure.",
        "",
        "## Workflow",
        "",
        "1. Run scaffold command to create placeholder files.",
        "2. Run verification command to validate required modules exist.",
        "3. Execute CI command to keep the branch green.",
        "",
        "## Required Scaffold Files",
        "",
    ]

    for layer, files in PHASE2_SCAFFOLD.items():
        lines.append(f"### {layer}")
        for name in files:
            lines.append(f"- {name}")
        lines.append("")

    plan_path.write_text("\n".join(lines), encoding="utf-8")
    return plan_path


def scaffold_phase2() -> Tuple[int, int]:
    root = _project_root()
    created = 0
    skipped = 0

    for layer, files in PHASE2_SCAFFOLD.items():
        layer_dir = root / "agent" / layer
        layer_dir.mkdir(parents=True, exist_ok=True)

        init_file = layer_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text(f'"""{layer} package."""\n', encoding="utf-8")
            created += 1

        for name in files:
            target = layer_dir / name
            if target.exists():
                skipped += 1
                continue
            target.write_text(_template(layer, name), encoding="utf-8")
            created += 1

    plan_path = generate_phase2_plan()
    console.print(f"[green]Generated plan:[/green] {plan_path}")
    return created, skipped


def verify_phase2() -> bool:
    root = _project_root()
    table = Table(title="Phase 2 Scaffold Verification", show_header=True)
    table.add_column("Layer")
    table.add_column("File")
    table.add_column("Status")

    missing = 0

    for layer, files in PHASE2_SCAFFOLD.items():
        for name in files:
            target = root / "agent" / layer / name
            if target.exists():
                table.add_row(layer, name, "OK")
            else:
                table.add_row(layer, name, "MISSING")
                missing += 1

    console.print(table)

    if missing == 0:
        console.print("[bold green]Phase 2 scaffold verification passed.[/bold green]")
        return True

    console.print(f"[bold red]Phase 2 scaffold verification failed: {missing} missing file(s).[/bold red]")
    return False
